- [x] Atualizar a interface de props do `AulaTemplate` em `shared.tsx`.
- [x] Implementar a lógica de exibição do `showCompletionBadge` no JSX do `AulaTemplate`.
- [x] Verificar a correção do TypeScript no `AulaVocabulary.tsx`.
- [x] Validar visualmente (se possível via leitura de código) outros arquivos afetados.
