# User role verification (Analista de Sistemas - Geociencias/TI)
- [x] 1. Navigates to `http://localhost:3000/login`
- [x] 2. Login with `andrehugo-analista-sistemas-sup` / `andrehugo-analista-sistemas-sup`
- [x] 3. Logged successfully
- [x] 4. Navigate to `/aulas`
- [x] 5. Verify materials match for Analista de Sistemas
- [x] 6. Search for 'Bloco III - Arquitetura e BD'
- [x] 7. Access topics list for 'Bloco III - Arquitetura e BD'
- [x] 8. Verify the presence of topics (ex: Lógica de programação)
- [x] 9. Navigate to a topic page (e.g. 'Lógica de programação')
- [x] 10. Verify premium placeholder layout
- [x] 11. Screenshot ementa page
- [x] 12. Screenshot placeholder page
- [x] 13. Test direct access to `/aulas/especifica-bloco-iii-arquitetura-e-bd` (404 fallback check)
- [x] 14. Report findings and confirm UI matches requirements
